p8105_hw2_ah4167
================
Aiying Huang
2023-09-26

# problem 1

``` r
options(scipen=999)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### First, clean the data in pols-month.csv. Use separate() to break up the variable mon into integer variables year, month, and day; replace month number with month name; create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.

``` r
pols_month_df=
  read.csv("./data/fivethirtyeight_datasets/pols-month.csv")|>
  separate(
           col="mon",
           into=c("year","month","day"),
           sep="-")|>
  mutate(
    month=case_match(
      month,
    "01"~"Jan",
    "02"~"Feb",
    "03"~"Mar",
    "04"~"Apr",
    "05"~"May",
    "06"~"Jun",
    "07"~"Jul",
    "08"~"Aug",
    "09"~"Sep",
    "10"~"Oct",
    "11"~"Nov",
    "12"~"Dec")
  )|>
  mutate(
    president=case_match(
      prez_gop,
    0~"dem",
    1~"gop"
    )
  )|>
  mutate(year,year=as.numeric(year))|>
  select(-starts_with("prez_"))|>
  select(-day)
```

### Second, clean the data in snp.csv using a similar process to the above. For consistency across datasets, arrange according to year and month, and organize so that year and month are the leading columns.

``` r
snp_df_1=
  read.csv("./data/fivethirtyeight_datasets/snp.csv")|>
  head(175)|>
  separate(
           col="date",
           into=c("year","month","day"),
           sep="/")|>
  mutate(
    year=case_match(
      year,
      "1"~2001,
    "2"~2002,
    "3"~2003,
    "4"~2004,
    "5"~2005,
    "6"~2006,
    "7"~2007,
    "8"~2008,
    "9"~2009,
    "10"~2010,
    "11"~2011,
    "12"~2012
    ),
    month=case_match(
      month,
    "1"~"Jan",
    "2"~"Feb",
    "3"~"Mar",
    "4"~"Apr",
    "5"~"May",
    "6"~"Jun",
    "7"~"Jul",
    "8"~"Aug",
    "9"~"Sep",
    "10"~"Oct",
    "11"~"Nov",
    "12"~"Dec")
  )|>
  select(-day)
```

``` r
snp_df_2=
  read.csv("./data/fivethirtyeight_datasets/snp.csv",skip=175)|>
  separate(
           col="X1.2.01",
           into=c("month","day","year"),
           sep="/")|>
  mutate(
    year=1900+as.numeric(year),
    month=case_match(
      month,
    "1"~"Jan",
    "2"~"Feb",
    "3"~"Mar",
    "4"~"Apr",
    "5"~"May",
    "6"~"Jun",
    "7"~"Jul",
    "8"~"Aug",
    "9"~"Sep",
    "10"~"Oct",
    "11"~"Nov",
    "12"~"Dec")
  )|>
  mutate(
    year=replace(year,year==1900,2000)
  )|>
  select(-day)|>
  rename(close=X1366.01001)
```

``` r
snp_df=
  bind_rows(snp_df_1,snp_df_2)|>
  arrange(year,month)
```

### Third, tidy the unemployment data so that it can be merged with the previous datasets. This process will involve switching from “wide” to “long” format; ensuring that key variables have the same name; and ensuring that key variables take the same values.

``` r
unemployment_df=
  read.csv("./data/fivethirtyeight_datasets/unemployment.csv")|>
  pivot_longer(
    Jan:Dec,
    names_to="month",
    values_to="unemployment"
  )|>
  janitor::clean_names()
```

### Join the datasets by merging snp into pols, and merging unemployment into the result.

``` r
Joint_df=
  left_join(pols_month_df,snp_df,by=c("year","month"))
final_merged_data <- left_join(Joint_df, unemployment_df, by = c("year","month"))
```

### Write a short paragraph about these datasets. Explain briefly what each dataset contained, and describe the resulting dataset (e.g. give the dimension, range of years, and names of key variables).

------------------------------------------------------------------------

# Problem 2

### Read and clean the Mr. Trash Wheel sheet:

- specify the sheet in the Excel file and to omit non-data entries (rows
  with notes / figures; columns containing notes) using arguments in
  read_excel
- use reasonable variable names
- omit rows that do not include dumpster-specific data

### The data include a column for the (approximate) number of homes powered. This calculation is described in the Homes powered note, but not applied to every row in the dataset. Update the data to include a new homes_powered variable based on this calculation.

``` r
Mr_Trash_Wheel_df=
  readxl::read_excel("./data/202207 Trash Wheel Collection Data.xlsx",sheet="Mr. Trash Wheel",range="A2:N549")|>
  janitor::clean_names()|>
  mutate(homes_powered=weight_tons*500/30)|>
  mutate(wheel_type="Mr")|>
  mutate(year,year=as.numeric(year))
```

### Use a similar process to import, clean, and organize the data for Professor Trash Wheel and Gwynnda, and combine these with the Mr. Trash Wheel dataset to produce a single tidy dataset. To keep track of which Trash Wheel is which, you may need to add an additional variable to all datasets before combining.

``` r
Professor_Trash_Wheel_df=
  readxl::read_excel("./data/202207 Trash Wheel Collection Data.xlsx",sheet="Professor Trash Wheel",range="A2:M96")|>
  janitor::clean_names()|>
  mutate(homes_powered=weight_tons*500/30)|>
  mutate(wheel_type="Professor")

Gwynnda_Trash_Wheel_df=
  readxl::read_excel("./data/202207 Trash Wheel Collection Data.xlsx",sheet="Gwynnda Trash Wheel",range="A2:K108")|>
  janitor::clean_names()|>
  mutate(homes_powered=weight_tons*500/30)|>
  mutate(wheel_type="Gwynnda")
```

``` r
Trash_Wheel_df=
  bind_rows(Mr_Trash_Wheel_df,
            Professor_Trash_Wheel_df,
            Gwynnda_Trash_Wheel_df)|>
  relocate(wheel_type)
```

### Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in the resulting dataset, and give examples of key variables. For available data, what was the total weight of trash collected by Professor Trash Wheel? What was the total number of cigarette butts collected by Gwynnda in July of 2021?

The number of observations in the resulting dataset is 747. There are 16
variables. We can tell from the resulting dataset that from 2014 to 2022
, the number of homes powered by trash recorded by this survey is about
37488. The total weight of trash collected by Professor Trash Wheel is
190.12. The the total number of cigarette butts collected by Gwynnda in
July of 2021 is 16300. All of those suggest that this project is
meaningful and it really did a lot in trash collecting and making it
useful to the public.

# Problem 3

### Import, clean, and tidy the dataset of baseline demographics. Ensure that sex and APOE4 carrier status are appropriate encoded (i.e. not numeric), and remove any participants who do not meet the stated inclusion criteria (i.e. no MCI at baseline).

``` r
baseline_df=read.csv("./data/data_mci/MCI_baseline.csv",skip=1)|>
  janitor::clean_names()|>
  mutate(
    sex=case_match(
      sex,
      0~"Male",
      1~"Female"
    ))|>
  mutate(
    apoe4=case_match(
      apoe4,
      0~"non-carrier",
      1~"APOE4 carrier"
    )
  )|>
  subset(
    age_at_onset!="."
  )
```

### Discuss important steps in the import process and relevant features of the dataset. How many participants were recruited, and of these how many develop MCI? What is the average baseline age? What proportion of women in the study are APOE4 carriers?

There are 483 participants recruited, 97 of these develop MCI. The
average baseline age is about 66. The proprtion of women in the study
are APOE4 carriers is 0.6078431.

### Similarly, import, clean, and tidy the dataset of longitudinally observed biomarker values; comment on the steps on the import process and the features of the dataset.

``` r
mci_amyloid_df=read.csv("./data/data_mci/mci_amyloid.csv",skip=1)|>
  janitor::clean_names()|>
  subset(
   baseline!="NA"& baseline!="Na"
  )|>
  rename(
  id=study_id
  )
```

I firstly import the data and omit non-data entries. Then I remove any
participants who have no MCI at baseline. Finally, to better combine two
datasets, I change the row name “study_id” to “id”, which is the same as
the row name of baseline_df. There are 487 participants recruited, 485
of them have the biomarker at the baseline. The proportion of those
participants who complete the whole process is 0.7134021.

### Check whether some participants appear in only the baseline or amyloid datasets, and comment on your findings. Combine the demographic and biomarker datasets so that only participants who appear in both datasets are retained, and briefly describe the resulting dataset; export the result as a CSV to your data directory.

``` r
left_join_df=
  left_join(baseline_df,mci_amyloid_df,by="id")
only_in_baseline_df=
  left_join_df|>
  subset(
    is.na(left_join_df$baseline))
only_in_baseline_df
```

    ##     id current_age    sex education         apoe4 age_at_onset baseline time_2
    ## 5   14        58.4   Male        20   non-carrier         66.2     <NA>   <NA>
    ## 13  49        64.7 Female        16   non-carrier         68.4     <NA>   <NA>
    ## 48 268        61.4   Male        18 APOE4 carrier         67.5     <NA>   <NA>
    ##    time_4 time_6 time_8
    ## 5    <NA>   <NA>   <NA>
    ## 13   <NA>   <NA>   <NA>
    ## 48   <NA>   <NA>   <NA>

There are three participants appear in only the baseline, there ids are
14, 49, and 268.

``` r
right_join_df=
  right_join(baseline_df,mci_amyloid_df,by="id")
only_in_amyloid_df=
  right_join_df|>
  subset(
    is.na(right_join_df$age_at_onset))
only_in_amyloid_df
```

    ##      id current_age  sex education apoe4 age_at_onset    baseline      time_2
    ## 95    1          NA <NA>        NA  <NA>         <NA>   0.1105487        <NA>
    ## 96    2          NA <NA>        NA  <NA>         <NA> 0.107481183 0.109157373
    ## 97    4          NA <NA>        NA  <NA>         <NA> 0.109251358 0.108699686
    ## 98    6          NA <NA>        NA  <NA>         <NA> 0.112426974 0.112853415
    ## 99    8          NA <NA>        NA  <NA>         <NA> 0.109563372 0.109470828
    ## 100   9          NA <NA>        NA  <NA>         <NA> 0.112101884 0.109781199
    ## 101  10          NA <NA>        NA  <NA>         <NA>   0.1116094 0.111592149
    ## 102  11          NA <NA>        NA  <NA>         <NA> 0.109119335 0.109316496
    ## 103  12          NA <NA>        NA  <NA>         <NA> 0.112042298 0.114167481
    ## 104  15          NA <NA>        NA  <NA>         <NA> 0.111544948        <NA>
    ## 105  16          NA <NA>        NA  <NA>         <NA> 0.110218888 0.113741328
    ## 106  17          NA <NA>        NA  <NA>         <NA> 0.108399246 0.113317542
    ## 107  19          NA <NA>        NA  <NA>         <NA> 0.106989637 0.105861947
    ## 108  20          NA <NA>        NA  <NA>         <NA> 0.109546355 0.114905811
    ## 109  21          NA <NA>        NA  <NA>         <NA> 0.112307333        <NA>
    ## 110  23          NA <NA>        NA  <NA>         <NA> 0.114131595 0.106741733
    ## 111  24          NA <NA>        NA  <NA>         <NA> 0.116402071 0.111696923
    ## 112  25          NA <NA>        NA  <NA>         <NA> 0.112064705 0.111500661
    ## 113  27          NA <NA>        NA  <NA>         <NA> 0.110989538 0.106955781
    ## 114  28          NA <NA>        NA  <NA>         <NA> 0.115005658 0.115655949
    ## 115  29          NA <NA>        NA  <NA>         <NA> 0.115129874 0.112980122
    ## 116  31          NA <NA>        NA  <NA>         <NA> 0.109918477 0.108271983
    ## 117  32          NA <NA>        NA  <NA>         <NA> 0.113900561 0.110762481
    ## 118  33          NA <NA>        NA  <NA>         <NA>  0.11282421 0.110933268
    ## 119  34          NA <NA>        NA  <NA>         <NA> 0.104993684 0.104423118
    ## 120  35          NA <NA>        NA  <NA>         <NA> 0.111469634  0.11528595
    ## 121  36          NA <NA>        NA  <NA>         <NA> 0.113243449 0.108346174
    ## 122  37          NA <NA>        NA  <NA>         <NA> 0.112698425 0.114833189
    ## 123  38          NA <NA>        NA  <NA>         <NA> 0.112078587 0.106174978
    ## 124  40          NA <NA>        NA  <NA>         <NA> 0.110273161 0.106484944
    ## 125  41          NA <NA>        NA  <NA>         <NA> 0.116358895  0.11123813
    ## 126  42          NA <NA>        NA  <NA>         <NA> 0.111611943 0.112288748
    ## 127  44          NA <NA>        NA  <NA>         <NA>  0.11033457 0.106889675
    ## 128  46          NA <NA>        NA  <NA>         <NA> 0.109471438 0.115916407
    ## 129  47          NA <NA>        NA  <NA>         <NA> 0.110545321 0.106081847
    ## 130  48          NA <NA>        NA  <NA>         <NA> 0.110589751 0.118265809
    ## 131  50          NA <NA>        NA  <NA>         <NA> 0.107169039  0.10473295
    ## 132  51          NA <NA>        NA  <NA>         <NA> 0.112642382 0.111428735
    ## 133  52          NA <NA>        NA  <NA>         <NA> 0.111360375        <NA>
    ## 134  53          NA <NA>        NA  <NA>         <NA> 0.112152275  0.11324751
    ## 135  54          NA <NA>        NA  <NA>         <NA>   0.1119746 0.113741518
    ## 136  56          NA <NA>        NA  <NA>         <NA> 0.109192332 0.109498539
    ## 137  57          NA <NA>        NA  <NA>         <NA> 0.108984035 0.107700573
    ## 138  58          NA <NA>        NA  <NA>         <NA> 0.114595933 0.111352261
    ## 139  60          NA <NA>        NA  <NA>         <NA> 0.117059602 0.108726723
    ## 140  61          NA <NA>        NA  <NA>         <NA> 0.111657594 0.110695476
    ## 141  62          NA <NA>        NA  <NA>         <NA> 0.116002304 0.108109054
    ## 142  63          NA <NA>        NA  <NA>         <NA> 0.110500693  0.10970472
    ## 143  64          NA <NA>        NA  <NA>         <NA> 0.112127194   0.1087145
    ## 144  66          NA <NA>        NA  <NA>         <NA> 0.111954901 0.110838014
    ## 145  68          NA <NA>        NA  <NA>         <NA> 0.113514969  0.11572734
    ## 146  70          NA <NA>        NA  <NA>         <NA>  0.11258955 0.110998288
    ## 147  71          NA <NA>        NA  <NA>         <NA> 0.111170052 0.117843678
    ## 148  74          NA <NA>        NA  <NA>         <NA>  0.11199154 0.111793054
    ## 149  79          NA <NA>        NA  <NA>         <NA> 0.109816232 0.112462775
    ## 150  80          NA <NA>        NA  <NA>         <NA> 0.114404744 0.112232425
    ## 151  81          NA <NA>        NA  <NA>         <NA> 0.111769129 0.113022403
    ## 152  82          NA <NA>        NA  <NA>         <NA> 0.106842105 0.109246944
    ## 153  83          NA <NA>        NA  <NA>         <NA> 0.110867514 0.108763415
    ## 154  84          NA <NA>        NA  <NA>         <NA> 0.109772289 0.111280123
    ## 155  85          NA <NA>        NA  <NA>         <NA> 0.112680791 0.110136142
    ## 156  88          NA <NA>        NA  <NA>         <NA> 0.113149962 0.114242052
    ## 157  90          NA <NA>        NA  <NA>         <NA> 0.111350211 0.108327816
    ## 158  91          NA <NA>        NA  <NA>         <NA> 0.108286598 0.108503416
    ## 159  93          NA <NA>        NA  <NA>         <NA> 0.107302948  0.10815066
    ## 160  94          NA <NA>        NA  <NA>         <NA>  0.11389369          Na
    ## 161  95          NA <NA>        NA  <NA>         <NA> 0.109724039 0.107726306
    ## 162  96          NA <NA>        NA  <NA>         <NA>  0.10882737 0.115567697
    ## 163  97          NA <NA>        NA  <NA>         <NA> 0.111474758 0.109985821
    ## 164  98          NA <NA>        NA  <NA>         <NA> 0.110120828 0.107460146
    ## 165  99          NA <NA>        NA  <NA>         <NA> 0.113739376 0.113836662
    ## 166 100          NA <NA>        NA  <NA>         <NA> 0.111809236 0.113480494
    ## 167 101          NA <NA>        NA  <NA>         <NA> 0.110027715 0.107126479
    ## 168 102          NA <NA>        NA  <NA>         <NA> 0.114021113 0.111891046
    ## 169 103          NA <NA>        NA  <NA>         <NA> 0.112685364 0.110353689
    ## 170 104          NA <NA>        NA  <NA>         <NA> 0.115247354 0.110250294
    ## 171 105          NA <NA>        NA  <NA>         <NA> 0.109296054 0.110609633
    ## 172 107          NA <NA>        NA  <NA>         <NA> 0.106831077 0.106743189
    ## 173 108          NA <NA>        NA  <NA>         <NA> 0.114386093 0.115448793
    ## 174 110          NA <NA>        NA  <NA>         <NA>  0.11508839 0.109565612
    ## 175 111          NA <NA>        NA  <NA>         <NA> 0.116854074 0.108924187
    ## 176 112          NA <NA>        NA  <NA>         <NA> 0.111255089 0.106622887
    ## 177 113          NA <NA>        NA  <NA>         <NA> 0.110601602 0.106395652
    ## 178 114          NA <NA>        NA  <NA>         <NA> 0.109260791 0.105549252
    ## 179 115          NA <NA>        NA  <NA>         <NA> 0.114378624 0.109972567
    ## 180 116          NA <NA>        NA  <NA>         <NA> 0.116560093 0.112065311
    ## 181 117          NA <NA>        NA  <NA>         <NA> 0.109024731 0.103151047
    ## 182 118          NA <NA>        NA  <NA>         <NA>  0.10623753 0.107475814
    ## 183 119          NA <NA>        NA  <NA>         <NA> 0.109791068  0.11174097
    ## 184 121          NA <NA>        NA  <NA>         <NA> 0.109994928 0.112206524
    ## 185 122          NA <NA>        NA  <NA>         <NA> 0.108602738 0.113932534
    ## 186 124          NA <NA>        NA  <NA>         <NA> 0.110921697 0.113305901
    ## 187 125          NA <NA>        NA  <NA>         <NA> 0.106641138 0.106757629
    ## 188 126          NA <NA>        NA  <NA>         <NA> 0.110768749  0.10899961
    ## 189 127          NA <NA>        NA  <NA>         <NA> 0.112047183 0.105310088
    ## 190 128          NA <NA>        NA  <NA>         <NA> 0.112333877 0.108568217
    ## 191 129          NA <NA>        NA  <NA>         <NA> 0.111652233 0.108378745
    ## 192 130          NA <NA>        NA  <NA>         <NA> 0.106989065        <NA>
    ## 193 131          NA <NA>        NA  <NA>         <NA> 0.110405798 0.113509815
    ## 194 133          NA <NA>        NA  <NA>         <NA> 0.110993066 0.110460449
    ## 195 134          NA <NA>        NA  <NA>         <NA> 0.107447162 0.112071846
    ## 196 135          NA <NA>        NA  <NA>         <NA> 0.115837765 0.111465011
    ## 197 136          NA <NA>        NA  <NA>         <NA> 0.115013925 0.111166502
    ## 198 137          NA <NA>        NA  <NA>         <NA>  0.11193317 0.114117575
    ## 199 138          NA <NA>        NA  <NA>         <NA> 0.110229076 0.104298316
    ## 200 139          NA <NA>        NA  <NA>         <NA> 0.115008273 0.113611653
    ## 201 140          NA <NA>        NA  <NA>         <NA> 0.116166175        <NA>
    ## 202 141          NA <NA>        NA  <NA>         <NA>  0.11309114 0.112172823
    ## 203 142          NA <NA>        NA  <NA>         <NA>  0.11423289 0.110216812
    ## 204 143          NA <NA>        NA  <NA>         <NA>   0.1112291 0.111009934
    ## 205 144          NA <NA>        NA  <NA>         <NA>  0.10947315 0.108971442
    ## 206 145          NA <NA>        NA  <NA>         <NA> 0.115590182 0.110950889
    ## 207 147          NA <NA>        NA  <NA>         <NA> 0.112108085 0.108528459
    ## 208 148          NA <NA>        NA  <NA>         <NA> 0.112054084 0.113265604
    ## 209 150          NA <NA>        NA  <NA>         <NA> 0.116264805 0.116821506
    ## 210 151          NA <NA>        NA  <NA>         <NA> 0.113608163 0.108580916
    ## 211 152          NA <NA>        NA  <NA>         <NA> 0.111559953  0.11094917
    ## 212 153          NA <NA>        NA  <NA>         <NA> 0.113520275        <NA>
    ## 213 154          NA <NA>        NA  <NA>         <NA> 0.115357541 0.112842522
    ## 214 155          NA <NA>        NA  <NA>         <NA> 0.107989299 0.111849869
    ## 215 156          NA <NA>        NA  <NA>         <NA>  0.11327259 0.108405018
    ## 216 157          NA <NA>        NA  <NA>         <NA> 0.108814316 0.109086169
    ## 217 158          NA <NA>        NA  <NA>         <NA> 0.110799627  0.11301348
    ## 218 159          NA <NA>        NA  <NA>         <NA> 0.113930694 0.108507079
    ## 219 160          NA <NA>        NA  <NA>         <NA> 0.111869498 0.111419715
    ## 220 161          NA <NA>        NA  <NA>         <NA> 0.108052962 0.108523882
    ## 221 162          NA <NA>        NA  <NA>         <NA> 0.112475302 0.109124332
    ## 222 163          NA <NA>        NA  <NA>         <NA> 0.112747999 0.112757952
    ## 223 164          NA <NA>        NA  <NA>         <NA> 0.112159516 0.108272686
    ## 224 165          NA <NA>        NA  <NA>         <NA> 0.109260703 0.109352691
    ## 225 167          NA <NA>        NA  <NA>         <NA> 0.112697767 0.111124248
    ## 226 168          NA <NA>        NA  <NA>         <NA> 0.111097239 0.113362548
    ## 227 169          NA <NA>        NA  <NA>         <NA> 0.113709367 0.112876095
    ## 228 171          NA <NA>        NA  <NA>         <NA> 0.111764745        <NA>
    ## 229 172          NA <NA>        NA  <NA>         <NA> 0.112279065 0.109488967
    ## 230 173          NA <NA>        NA  <NA>         <NA>  0.10665628 0.107544877
    ## 231 174          NA <NA>        NA  <NA>         <NA> 0.113870695 0.105367393
    ## 232 175          NA <NA>        NA  <NA>         <NA> 0.110447213 0.109257868
    ## 233 176          NA <NA>        NA  <NA>         <NA> 0.113669694 0.110842203
    ## 234 178          NA <NA>        NA  <NA>         <NA> 0.110403961 0.111385633
    ## 235 180          NA <NA>        NA  <NA>         <NA> 0.113806433        <NA>
    ## 236 181          NA <NA>        NA  <NA>         <NA> 0.109548645 0.111917541
    ## 237 182          NA <NA>        NA  <NA>         <NA> 0.108484174 0.111536146
    ## 238 183          NA <NA>        NA  <NA>         <NA> 0.108565576 0.106722774
    ## 239 184          NA <NA>        NA  <NA>         <NA> 0.118215335        <NA>
    ## 240 185          NA <NA>        NA  <NA>         <NA> 0.111091191 0.111206684
    ## 241 187          NA <NA>        NA  <NA>         <NA> 0.109763067 0.107664395
    ## 242 188          NA <NA>        NA  <NA>         <NA>  0.11313781 0.110913977
    ## 243 189          NA <NA>        NA  <NA>         <NA> 0.111063049 0.113349902
    ## 244 190          NA <NA>        NA  <NA>         <NA>  0.11589442 0.112072935
    ## 245 191          NA <NA>        NA  <NA>         <NA> 0.109465952 0.113946316
    ## 246 192          NA <NA>        NA  <NA>         <NA> 0.105397136 0.105887324
    ## 247 193          NA <NA>        NA  <NA>         <NA> 0.112570898 0.109856279
    ## 248 194          NA <NA>        NA  <NA>         <NA> 0.107667466  0.10454562
    ## 249 195          NA <NA>        NA  <NA>         <NA>  0.11018114 0.107946141
    ## 250 196          NA <NA>        NA  <NA>         <NA> 0.113560672 0.112007202
    ## 251 197          NA <NA>        NA  <NA>         <NA> 0.112997226        <NA>
    ## 252 198          NA <NA>        NA  <NA>         <NA> 0.116171582 0.113983608
    ## 253 199          NA <NA>        NA  <NA>         <NA> 0.112244767 0.109552653
    ## 254 200          NA <NA>        NA  <NA>         <NA> 0.112462358 0.109221298
    ## 255 201          NA <NA>        NA  <NA>         <NA> 0.108098798 0.109902594
    ## 256 203          NA <NA>        NA  <NA>         <NA> 0.108481607 0.108858361
    ## 257 204          NA <NA>        NA  <NA>         <NA> 0.113843587 0.107294914
    ## 258 205          NA <NA>        NA  <NA>         <NA> 0.110405326 0.108214953
    ## 259 206          NA <NA>        NA  <NA>         <NA> 0.105185791 0.106223307
    ## 260 207          NA <NA>        NA  <NA>         <NA> 0.110261676 0.108526325
    ## 261 208          NA <NA>        NA  <NA>         <NA> 0.110355973 0.108300166
    ## 262 209          NA <NA>        NA  <NA>         <NA> 0.112530533 0.114170609
    ## 263 210          NA <NA>        NA  <NA>         <NA> 0.108214487 0.110188868
    ## 264 211          NA <NA>        NA  <NA>         <NA> 0.114137467 0.111451901
    ## 265 212          NA <NA>        NA  <NA>         <NA> 0.107937409  0.10639588
    ## 266 213          NA <NA>        NA  <NA>         <NA>  0.11299686 0.112907947
    ## 267 214          NA <NA>        NA  <NA>         <NA> 0.112598517 0.110321332
    ## 268 215          NA <NA>        NA  <NA>         <NA> 0.111034389 0.109935172
    ## 269 216          NA <NA>        NA  <NA>         <NA> 0.109018937        <NA>
    ## 270 217          NA <NA>        NA  <NA>         <NA> 0.114991488 0.111271838
    ## 271 219          NA <NA>        NA  <NA>         <NA> 0.107481863  0.10477106
    ## 272 220          NA <NA>        NA  <NA>         <NA> 0.109545897 0.113029162
    ## 273 221          NA <NA>        NA  <NA>         <NA> 0.115256723 0.114218397
    ## 274 222          NA <NA>        NA  <NA>         <NA>  0.10719587 0.112179679
    ## 275 223          NA <NA>        NA  <NA>         <NA> 0.108381993 0.107049412
    ## 276 224          NA <NA>        NA  <NA>         <NA> 0.112909545 0.112770958
    ## 277 225          NA <NA>        NA  <NA>         <NA> 0.114814304 0.115060301
    ## 278 227          NA <NA>        NA  <NA>         <NA> 0.109379357        <NA>
    ## 279 228          NA <NA>        NA  <NA>         <NA> 0.112070123 0.116015774
    ## 280 231          NA <NA>        NA  <NA>         <NA>  0.11458089 0.109402445
    ## 281 232          NA <NA>        NA  <NA>         <NA>  0.11595142        <NA>
    ## 282 233          NA <NA>        NA  <NA>         <NA> 0.112893833 0.115013335
    ## 283 235          NA <NA>        NA  <NA>         <NA>  0.11137802 0.111378396
    ## 284 236          NA <NA>        NA  <NA>         <NA>  0.11558541        <NA>
    ## 285 237          NA <NA>        NA  <NA>         <NA> 0.113196582  0.10900657
    ## 286 238          NA <NA>        NA  <NA>         <NA> 0.112606834 0.116397819
    ## 287 239          NA <NA>        NA  <NA>         <NA> 0.113600797 0.106647566
    ## 288 240          NA <NA>        NA  <NA>         <NA> 0.107417229 0.105284921
    ## 289 241          NA <NA>        NA  <NA>         <NA> 0.110868908  0.11549979
    ## 290 243          NA <NA>        NA  <NA>         <NA> 0.112000253 0.108916554
    ## 291 244          NA <NA>        NA  <NA>         <NA> 0.113622725 0.111634374
    ## 292 245          NA <NA>        NA  <NA>         <NA> 0.110709106 0.111442223
    ## 293 246          NA <NA>        NA  <NA>         <NA> 0.107236319        <NA>
    ## 294 247          NA <NA>        NA  <NA>         <NA> 0.112413078 0.111275404
    ## 295 248          NA <NA>        NA  <NA>         <NA> 0.109496789 0.110915407
    ## 296 251          NA <NA>        NA  <NA>         <NA> 0.113267198 0.112860254
    ## 297 253          NA <NA>        NA  <NA>         <NA> 0.115134627 0.110547291
    ## 298 254          NA <NA>        NA  <NA>         <NA> 0.110245956 0.108772293
    ## 299 255          NA <NA>        NA  <NA>         <NA> 0.106253475 0.110105251
    ## 300 256          NA <NA>        NA  <NA>         <NA> 0.110333058 0.111191436
    ## 301 257          NA <NA>        NA  <NA>         <NA>  0.11543654 0.113668756
    ## 302 258          NA <NA>        NA  <NA>         <NA> 0.112868713 0.113611195
    ## 303 259          NA <NA>        NA  <NA>         <NA> 0.108453633 0.109658783
    ## 304 260          NA <NA>        NA  <NA>         <NA> 0.109796797 0.110224005
    ## 305 261          NA <NA>        NA  <NA>         <NA> 0.103748954 0.107379199
    ## 306 262          NA <NA>        NA  <NA>         <NA> 0.109446465 0.111668885
    ## 307 263          NA <NA>        NA  <NA>         <NA> 0.114413693 0.118711732
    ## 308 264          NA <NA>        NA  <NA>         <NA> 0.109290417 0.107052575
    ## 309 265          NA <NA>        NA  <NA>         <NA> 0.111600682 0.109383354
    ## 310 266          NA <NA>        NA  <NA>         <NA>  0.11336981 0.111157775
    ## 311 267          NA <NA>        NA  <NA>         <NA> 0.114340797 0.116760903
    ## 312 269          NA <NA>        NA  <NA>         <NA> 0.110360136 0.108676655
    ## 313 270          NA <NA>        NA  <NA>         <NA>  0.11031577        <NA>
    ## 314 271          NA <NA>        NA  <NA>         <NA> 0.110585716 0.110450742
    ## 315 272          NA <NA>        NA  <NA>         <NA> 0.106047845 0.102522548
    ## 316 273          NA <NA>        NA  <NA>         <NA> 0.111687203 0.112214262
    ## 317 274          NA <NA>        NA  <NA>         <NA> 0.109256855 0.109016523
    ## 318 275          NA <NA>        NA  <NA>         <NA> 0.113862157 0.113152705
    ## 319 276          NA <NA>        NA  <NA>         <NA> 0.103669628        <NA>
    ## 320 278          NA <NA>        NA  <NA>         <NA> 0.107788079 0.108533987
    ## 321 279          NA <NA>        NA  <NA>         <NA> 0.110001275  0.11353116
    ## 322 281          NA <NA>        NA  <NA>         <NA> 0.110473547 0.108010138
    ## 323 282          NA <NA>        NA  <NA>         <NA> 0.104402165 0.108249718
    ## 324 284          NA <NA>        NA  <NA>         <NA> 0.110562425 0.108796483
    ## 325 285          NA <NA>        NA  <NA>         <NA> 0.110865277 0.109180323
    ## 326 288          NA <NA>        NA  <NA>         <NA>  0.11249236 0.110777255
    ## 327 290          NA <NA>        NA  <NA>         <NA> 0.111066618 0.111884626
    ## 328 291          NA <NA>        NA  <NA>         <NA> 0.112938689 0.112360489
    ## 329 293          NA <NA>        NA  <NA>         <NA> 0.111427155        <NA>
    ## 330 294          NA <NA>        NA  <NA>         <NA> 0.109276532 0.113026569
    ## 331 295          NA <NA>        NA  <NA>         <NA> 0.115606685        <NA>
    ## 332 296          NA <NA>        NA  <NA>         <NA> 0.112392331        <NA>
    ## 333 298          NA <NA>        NA  <NA>         <NA> 0.105798635 0.112435931
    ## 334 299          NA <NA>        NA  <NA>         <NA> 0.116699121 0.109227089
    ## 335 300          NA <NA>        NA  <NA>         <NA> 0.109040582 0.108295985
    ## 336 302          NA <NA>        NA  <NA>         <NA> 0.112249076 0.113542483
    ## 337 303          NA <NA>        NA  <NA>         <NA> 0.111620081 0.110791889
    ## 338 307          NA <NA>        NA  <NA>         <NA> 0.115482975 0.107838911
    ## 339 308          NA <NA>        NA  <NA>         <NA> 0.107487702          Na
    ## 340 309          NA <NA>        NA  <NA>         <NA> 0.113399772 0.110750724
    ## 341 310          NA <NA>        NA  <NA>         <NA> 0.109270887 0.109795055
    ## 342 311          NA <NA>        NA  <NA>         <NA> 0.109151165 0.116141701
    ## 343 312          NA <NA>        NA  <NA>         <NA> 0.113459428    0.112235
    ## 344 313          NA <NA>        NA  <NA>         <NA>  0.11398153  0.10963414
    ## 345 315          NA <NA>        NA  <NA>         <NA> 0.113616693 0.108476844
    ## 346 316          NA <NA>        NA  <NA>         <NA> 0.110549067 0.109248731
    ## 347 317          NA <NA>        NA  <NA>         <NA> 0.112034133 0.112309047
    ## 348 318          NA <NA>        NA  <NA>         <NA> 0.115707722  0.11007876
    ## 349 319          NA <NA>        NA  <NA>         <NA> 0.109862404 0.111428595
    ## 350 320          NA <NA>        NA  <NA>         <NA> 0.105694718 0.111338767
    ## 351 321          NA <NA>        NA  <NA>         <NA> 0.110760407 0.109764055
    ## 352 322          NA <NA>        NA  <NA>         <NA> 0.110046891   0.1071658
    ## 353 324          NA <NA>        NA  <NA>         <NA> 0.117636767 0.110695721
    ## 354 325          NA <NA>        NA  <NA>         <NA> 0.111746455 0.110269495
    ## 355 326          NA <NA>        NA  <NA>         <NA> 0.110459106 0.108283669
    ## 356 327          NA <NA>        NA  <NA>         <NA> 0.115914075 0.116057447
    ## 357 329          NA <NA>        NA  <NA>         <NA> 0.118405048 0.115540114
    ## 358 330          NA <NA>        NA  <NA>         <NA> 0.108252386 0.111444278
    ## 359 331          NA <NA>        NA  <NA>         <NA> 0.110435676 0.112514085
    ## 360 332          NA <NA>        NA  <NA>         <NA> 0.111728742 0.108822039
    ## 361 333          NA <NA>        NA  <NA>         <NA> 0.111548636        <NA>
    ## 362 334          NA <NA>        NA  <NA>         <NA>  0.11141818        <NA>
    ## 363 335          NA <NA>        NA  <NA>         <NA> 0.111391532 0.111003399
    ## 364 339          NA <NA>        NA  <NA>         <NA> 0.110406213 0.112662758
    ## 365 340          NA <NA>        NA  <NA>         <NA> 0.113770508        <NA>
    ## 366 341          NA <NA>        NA  <NA>         <NA> 0.111485238 0.112988368
    ## 367 342          NA <NA>        NA  <NA>         <NA> 0.112281092 0.110454111
    ## 368 343          NA <NA>        NA  <NA>         <NA> 0.109000592 0.110828555
    ## 369 344          NA <NA>        NA  <NA>         <NA> 0.104493777 0.111410573
    ## 370 345          NA <NA>        NA  <NA>         <NA> 0.116500043  0.11281317
    ## 371 346          NA <NA>        NA  <NA>         <NA> 0.110422587 0.108413615
    ## 372 353          NA <NA>        NA  <NA>         <NA> 0.111763353        <NA>
    ## 373 354          NA <NA>        NA  <NA>         <NA> 0.107791322 0.112454752
    ## 374 356          NA <NA>        NA  <NA>         <NA> 0.109379105 0.106965433
    ## 375 357          NA <NA>        NA  <NA>         <NA> 0.112494164  0.11410471
    ## 376 358          NA <NA>        NA  <NA>         <NA> 0.111928654 0.114038778
    ## 377 359          NA <NA>        NA  <NA>         <NA> 0.113600273 0.111886881
    ## 378 360          NA <NA>        NA  <NA>         <NA> 0.114141051        <NA>
    ## 379 361          NA <NA>        NA  <NA>         <NA> 0.109644487  0.10848668
    ## 380 362          NA <NA>        NA  <NA>         <NA> 0.108106556 0.110510273
    ## 381 363          NA <NA>        NA  <NA>         <NA> 0.113522295 0.117107644
    ## 382 364          NA <NA>        NA  <NA>         <NA> 0.115713628 0.114708754
    ## 383 367          NA <NA>        NA  <NA>         <NA> 0.117689024 0.113237952
    ## 384 368          NA <NA>        NA  <NA>         <NA> 0.113687194  0.11075241
    ## 385 370          NA <NA>        NA  <NA>         <NA> 0.110829401   0.1073372
    ## 386 371          NA <NA>        NA  <NA>         <NA> 0.110945361 0.106288231
    ## 387 372          NA <NA>        NA  <NA>         <NA> 0.111068016 0.109760332
    ## 388 374          NA <NA>        NA  <NA>         <NA> 0.112892498 0.109846788
    ## 389 375          NA <NA>        NA  <NA>         <NA> 0.116373615 0.114045047
    ## 390 376          NA <NA>        NA  <NA>         <NA> 0.106348819        <NA>
    ## 391 378          NA <NA>        NA  <NA>         <NA> 0.109343275 0.106164941
    ## 392 381          NA <NA>        NA  <NA>         <NA> 0.105097823 0.105778185
    ## 393 382          NA <NA>        NA  <NA>         <NA> 0.110064878 0.108051924
    ## 394 383          NA <NA>        NA  <NA>         <NA> 0.115607319 0.113823446
    ## 395 384          NA <NA>        NA  <NA>         <NA> 0.116961073 0.111892878
    ## 396 385          NA <NA>        NA  <NA>         <NA> 0.109777183  0.11124558
    ## 397 386          NA <NA>        NA  <NA>         <NA>  0.11034442  0.10479554
    ## 398 387          NA <NA>        NA  <NA>         <NA> 0.109151568 0.110664587
    ## 399 388          NA <NA>        NA  <NA>         <NA> 0.111076193 0.112819993
    ## 400 390          NA <NA>        NA  <NA>         <NA> 0.111920365 0.113983819
    ## 401 391          NA <NA>        NA  <NA>         <NA>  0.10836807 0.108527408
    ## 402 392          NA <NA>        NA  <NA>         <NA> 0.116843254 0.106764016
    ## 403 393          NA <NA>        NA  <NA>         <NA> 0.113067002 0.108511981
    ## 404 394          NA <NA>        NA  <NA>         <NA> 0.107519754 0.109540134
    ## 405 395          NA <NA>        NA  <NA>         <NA> 0.111582619 0.107791941
    ## 406 396          NA <NA>        NA  <NA>         <NA> 0.113999488 0.110374196
    ## 407 397          NA <NA>        NA  <NA>         <NA> 0.110763293  0.11086958
    ## 408 399          NA <NA>        NA  <NA>         <NA> 0.117121943  0.11711734
    ## 409 401          NA <NA>        NA  <NA>         <NA> 0.112569102 0.111576061
    ## 410 402          NA <NA>        NA  <NA>         <NA> 0.107932575 0.109955897
    ## 411 403          NA <NA>        NA  <NA>         <NA> 0.108716933 0.112528009
    ## 412 404          NA <NA>        NA  <NA>         <NA> 0.106223701 0.111414357
    ## 413 405          NA <NA>        NA  <NA>         <NA> 0.112091811 0.110110034
    ## 414 406          NA <NA>        NA  <NA>         <NA> 0.110644536 0.113750326
    ## 415 407          NA <NA>        NA  <NA>         <NA> 0.113153337 0.114635971
    ## 416 410          NA <NA>        NA  <NA>         <NA> 0.111475498        <NA>
    ## 417 411          NA <NA>        NA  <NA>         <NA>  0.10826737 0.104959222
    ## 418 413          NA <NA>        NA  <NA>         <NA> 0.108723744 0.111658125
    ## 419 414          NA <NA>        NA  <NA>         <NA> 0.112159297        <NA>
    ## 420 415          NA <NA>        NA  <NA>         <NA> 0.112331985 0.111208241
    ## 421 418          NA <NA>        NA  <NA>         <NA>  0.11162232        <NA>
    ## 422 420          NA <NA>        NA  <NA>         <NA>  0.10960311 0.111670212
    ## 423 421          NA <NA>        NA  <NA>         <NA> 0.113799342 0.107506943
    ## 424 422          NA <NA>        NA  <NA>         <NA> 0.106676555 0.105541532
    ## 425 425          NA <NA>        NA  <NA>         <NA> 0.111313214 0.110991653
    ## 426 427          NA <NA>        NA  <NA>         <NA> 0.110183865 0.109537729
    ## 427 428          NA <NA>        NA  <NA>         <NA> 0.109593275 0.111114254
    ## 428 429          NA <NA>        NA  <NA>         <NA>  0.10860544 0.112263306
    ## 429 430          NA <NA>        NA  <NA>         <NA> 0.111110976 0.113769421
    ## 430 432          NA <NA>        NA  <NA>         <NA>  0.10543651 0.110921688
    ## 431 433          NA <NA>        NA  <NA>         <NA>  0.11095067 0.112410406
    ## 432 434          NA <NA>        NA  <NA>         <NA> 0.114574762 0.110975001
    ## 433 435          NA <NA>        NA  <NA>         <NA> 0.109042458 0.110343846
    ## 434 436          NA <NA>        NA  <NA>         <NA> 0.104514207 0.110257977
    ## 435 437          NA <NA>        NA  <NA>         <NA> 0.108135916 0.105255451
    ## 436 438          NA <NA>        NA  <NA>         <NA> 0.111720018 0.107789231
    ## 437 439          NA <NA>        NA  <NA>         <NA> 0.109270125        <NA>
    ## 438 441          NA <NA>        NA  <NA>         <NA> 0.113751765        <NA>
    ## 439 443          NA <NA>        NA  <NA>         <NA>  0.10722303 0.108332103
    ## 440 444          NA <NA>        NA  <NA>         <NA> 0.113098331 0.109344515
    ## 441 445          NA <NA>        NA  <NA>         <NA> 0.110213517 0.112164768
    ## 442 446          NA <NA>        NA  <NA>         <NA> 0.106255778 0.110742988
    ## 443 447          NA <NA>        NA  <NA>         <NA> 0.114193915 0.113647613
    ## 444 450          NA <NA>        NA  <NA>         <NA> 0.110871392  0.11233316
    ## 445 451          NA <NA>        NA  <NA>         <NA> 0.103817071 0.106886333
    ## 446 454          NA <NA>        NA  <NA>         <NA> 0.107184782 0.112458593
    ## 447 455          NA <NA>        NA  <NA>         <NA> 0.114536385 0.113694314
    ## 448 456          NA <NA>        NA  <NA>         <NA> 0.113702455        <NA>
    ## 449 457          NA <NA>        NA  <NA>         <NA> 0.106417695 0.107201293
    ## 450 458          NA <NA>        NA  <NA>         <NA>  0.11242496 0.111832245
    ## 451 459          NA <NA>        NA  <NA>         <NA>  0.11079733 0.111978578
    ## 452 460          NA <NA>        NA  <NA>         <NA> 0.111177153 0.109035694
    ## 453 461          NA <NA>        NA  <NA>         <NA>  0.11131826 0.111722852
    ## 454 462          NA <NA>        NA  <NA>         <NA> 0.113264904 0.109714173
    ## 455 463          NA <NA>        NA  <NA>         <NA> 0.104653126 0.108005891
    ## 456 464          NA <NA>        NA  <NA>         <NA> 0.113219556 0.113897597
    ## 457 465          NA <NA>        NA  <NA>         <NA> 0.107501228 0.114188362
    ## 458 466          NA <NA>        NA  <NA>         <NA> 0.115142096 0.116062053
    ## 459 467          NA <NA>        NA  <NA>         <NA> 0.114514549  0.11092243
    ## 460 468          NA <NA>        NA  <NA>         <NA> 0.109642837        <NA>
    ## 461 469          NA <NA>        NA  <NA>         <NA> 0.108393823        <NA>
    ## 462 470          NA <NA>        NA  <NA>         <NA> 0.112726926 0.108474775
    ## 463 472          NA <NA>        NA  <NA>         <NA> 0.111204398 0.115584445
    ## 464 473          NA <NA>        NA  <NA>         <NA>  0.11055729 0.110901035
    ## 465 474          NA <NA>        NA  <NA>         <NA> 0.110554761 0.111891005
    ## 466 475          NA <NA>        NA  <NA>         <NA> 0.113232698 0.110865707
    ## 467 476          NA <NA>        NA  <NA>         <NA> 0.112312851 0.111471394
    ## 468 477          NA <NA>        NA  <NA>         <NA> 0.112624527 0.107853728
    ## 469 478          NA <NA>        NA  <NA>         <NA>  0.11201055 0.115357869
    ## 470 479          NA <NA>        NA  <NA>         <NA> 0.105849802 0.106460984
    ## 471 480          NA <NA>        NA  <NA>         <NA> 0.115047403 0.109866698
    ## 472 481          NA <NA>        NA  <NA>         <NA> 0.113442174 0.112416335
    ## 473 482          NA <NA>        NA  <NA>         <NA> 0.116135142 0.114311943
    ## 474 483          NA <NA>        NA  <NA>         <NA> 0.108782286  0.10723613
    ## 475 484          NA <NA>        NA  <NA>         <NA>  0.11139422 0.110936838
    ## 476 485          NA <NA>        NA  <NA>         <NA> 0.106042813 0.105158363
    ## 477 486          NA <NA>        NA  <NA>         <NA> 0.109161071 0.114634379
    ## 478 487          NA <NA>        NA  <NA>         <NA> 0.110821971 0.107791347
    ## 479 488          NA <NA>        NA  <NA>         <NA> 0.110418756 0.111994328
    ## 480 489          NA <NA>        NA  <NA>         <NA>  0.11477384 0.113322128
    ## 481 490          NA <NA>        NA  <NA>         <NA> 0.111762756 0.109627815
    ## 482 491          NA <NA>        NA  <NA>         <NA> 0.116934974 0.113763228
    ## 483 492          NA <NA>        NA  <NA>         <NA> 0.109757685 0.109912273
    ## 484 493          NA <NA>        NA  <NA>         <NA> 0.108357146 0.108161281
    ## 485 494          NA <NA>        NA  <NA>         <NA> 0.116669151 0.109711076
    ##          time_4      time_6      time_8
    ## 95  0.109325197 0.104756131 0.107257697
    ## 96  0.109457839 0.105729713  0.10661845
    ## 97  0.110540386 0.107476797 0.111212209
    ## 98   0.11143945 0.110279277 0.114982747
    ## 99         <NA> 0.108742168 0.110268552
    ## 100 0.108832888        <NA>        <NA>
    ## 101        <NA>        <NA> 0.110051296
    ## 102   0.1114037 0.108586573 0.108993335
    ## 103 0.109859682 0.106842794 0.107334106
    ## 104 0.110798711 0.110378192 0.106742725
    ## 105 0.111101474 0.108852437 0.109556166
    ## 106 0.105909034 0.107196914 0.110199133
    ## 107 0.107371076 0.109003799 0.102666279
    ## 108 0.107900402 0.104254203        <NA>
    ## 109 0.108297956 0.110300812 0.108506223
    ## 110        <NA> 0.107469873 0.110544536
    ## 111 0.110232524 0.111166592 0.114258539
    ## 112        <NA> 0.108690215        <NA>
    ## 113 0.114806616 0.107115847 0.105972994
    ## 114 0.112172466 0.112449191 0.108843523
    ## 115   0.1118295 0.112608543 0.112497893
    ## 116 0.108206771 0.105681631 0.107525141
    ## 117 0.109443041 0.107025688  0.11116698
    ## 118          Na 0.110644516 0.106447411
    ## 119        <NA> 0.107896181 0.107087733
    ## 120 0.108868436 0.109639633 0.108461387
    ## 121 0.114211489 0.113578691 0.112382504
    ## 122 0.112628096 0.113016322 0.110599009
    ## 123 0.108917893 0.111679794 0.109003574
    ## 124  0.10625245 0.112426569 0.107214432
    ## 125 0.106242805 0.115597605        <NA>
    ## 126   0.1111357 0.107423818 0.106798468
    ## 127 0.114852972 0.108259502 0.108429063
    ## 128 0.113395876 0.111078341 0.113198416
    ## 129        <NA> 0.107847761  0.10662516
    ## 130 0.104885905 0.109693764 0.111567623
    ## 131 0.108557518 0.104577694 0.104070382
    ## 132        <NA> 0.109139703 0.110763947
    ## 133 0.105968742 0.101625243 0.108211349
    ## 134 0.109562093 0.110612356 0.111641956
    ## 135 0.112621732 0.107033715 0.110514169
    ## 136 0.109589217 0.106356285 0.106426905
    ## 137 0.109241877        <NA> 0.105709243
    ## 138 0.112874539 0.111821774 0.110010365
    ## 139 0.114616686 0.113010154 0.108289209
    ## 140 0.108442578 0.111418671 0.106864815
    ## 141 0.112990262 0.108264264 0.109523624
    ## 142 0.109146796 0.110698585 0.108102955
    ## 143 0.108195677 0.107059598 0.105631869
    ## 144 0.113296815  0.10903554 0.106355888
    ## 145  0.10879763 0.109832607 0.107130682
    ## 146 0.110323734 0.106420417 0.108667851
    ## 147 0.112303289 0.111873152 0.104601954
    ## 148 0.108314413 0.107177142 0.107072996
    ## 149 0.110359103 0.108465947 0.110077079
    ## 150 0.113650805 0.105629175 0.112047717
    ## 151  0.11429784 0.111346443 0.110568342
    ## 152 0.112949219 0.107515672 0.109695421
    ## 153 0.107042979 0.105112564 0.108152289
    ## 154 0.112429218 0.109864808 0.110974151
    ## 155 0.109738529 0.112317873        <NA>
    ## 156 0.117254569        <NA> 0.112467469
    ## 157 0.110971204 0.111208231 0.109673371
    ## 158 0.104867456 0.107243697 0.103342003
    ## 159 0.102894277 0.107999958  0.10394613
    ## 160 0.113000849  0.10867866 0.112277473
    ## 161 0.109543387        <NA> 0.105829673
    ## 162 0.107410972 0.110039381 0.107708336
    ## 163 0.109112853 0.108639427 0.107794924
    ## 164 0.111702393 0.108042001        <NA>
    ## 165 0.112302961  0.10970711 0.111980619
    ## 166 0.108741417 0.112060616 0.108496272
    ## 167 0.114302597        <NA> 0.109217169
    ## 168        <NA> 0.105846926 0.109321568
    ## 169  0.11297875 0.110669275 0.112546477
    ## 170 0.109044095  0.11062238 0.112816101
    ## 171 0.110215796  0.11197232  0.11586455
    ## 172 0.106388181 0.106368477 0.109349326
    ## 173 0.106225786 0.108570637 0.111220793
    ## 174 0.113467325 0.110730718 0.109706311
    ## 175        <NA>  0.11040878 0.108420012
    ## 176 0.107405587 0.111182267 0.109703985
    ## 177 0.105653459 0.104944529 0.103201994
    ## 178 0.108490992 0.106399534 0.107797014
    ## 179 0.109285194  0.10946718 0.107488455
    ## 180 0.113491941  0.11171185 0.113371387
    ## 181  0.10950157 0.105328335 0.107953773
    ## 182 0.105855583 0.105872981 0.104382242
    ## 183 0.107977703 0.109350074 0.108662675
    ## 184    0.116631 0.114170985  0.11071067
    ## 185 0.108209099 0.106157812 0.104543774
    ## 186 0.109506095        <NA> 0.108994442
    ## 187 0.112118455 0.107412383        <NA>
    ## 188 0.110787402  0.10550369 0.111256569
    ## 189 0.109286554 0.109626315  0.11433579
    ## 190 0.110533413 0.108530887 0.106439307
    ## 191 0.117970399        <NA>  0.11186096
    ## 192 0.109311089 0.105528678 0.106655128
    ## 193 0.109604924 0.111704822 0.110250155
    ## 194 0.110122531 0.115577617 0.109602344
    ## 195 0.108722076 0.111803485 0.108162058
    ## 196 0.109640025 0.114620782          Na
    ## 197 0.115401195 0.112998492 0.110384898
    ## 198 0.109088028 0.109061272 0.111009139
    ## 199  0.10770547 0.104200884 0.104660178
    ## 200 0.110264797 0.107995736 0.110052978
    ## 201 0.112098521 0.110705025 0.112229408
    ## 202 0.108161214 0.103344036 0.107180501
    ## 203 0.108580769  0.10495667  0.10735787
    ## 204  0.11188745 0.110505947 0.113182982
    ## 205 0.109181603 0.110871641 0.115172267
    ## 206 0.109407603 0.113288423 0.110477904
    ## 207 0.104723614        <NA> 0.110421066
    ## 208 0.109892049        <NA>  0.11074136
    ## 209 0.111890244 0.111029241 0.110733996
    ## 210        <NA> 0.108361232 0.105491237
    ## 211 0.111302618 0.112019038 0.113345844
    ## 212 0.113732454 0.111485554 0.109185341
    ## 213 0.110617021 0.109017525 0.111596206
    ## 214 0.109039806 0.106468902 0.110687157
    ## 215 0.111582218 0.112479152 0.112304393
    ## 216 0.107297502 0.107029454 0.105370984
    ## 217 0.113852777 0.116274526 0.109467369
    ## 218 0.110776315  0.11479313 0.110638546
    ## 219 0.107228577        <NA>  0.10848435
    ## 220 0.106035669 0.104354121 0.107276016
    ## 221  0.10792853        <NA> 0.109852207
    ## 222 0.110345673        <NA>        <NA>
    ## 223 0.115087294  0.10709817 0.111019004
    ## 224 0.109101327 0.107393766 0.109186068
    ## 225        <NA> 0.110748097 0.108417124
    ## 226 0.115290461 0.109922399 0.109546537
    ## 227 0.109526265 0.108440872 0.108258147
    ## 228 0.107103936  0.10691259 0.106847156
    ## 229        <NA> 0.107735874 0.109390607
    ## 230 0.110430503 0.106024565        <NA>
    ## 231 0.111429822 0.110995589 0.115150942
    ## 232 0.115522341 0.110509351 0.109031623
    ## 233 0.108509164 0.112221473 0.110039067
    ## 234 0.110068277 0.104541101 0.106985618
    ## 235 0.114042045 0.107161884 0.107183292
    ## 236 0.109278334  0.11166621 0.108968217
    ## 237 0.107999137 0.107726194 0.105669413
    ## 238 0.104901171 0.106505678 0.106399583
    ## 239 0.111813137 0.114049341 0.108880233
    ## 240 0.105848361 0.111476008 0.106719007
    ## 241 0.108949405 0.109036073        <NA>
    ## 242 0.110622844 0.112630919  0.11298672
    ## 243 0.111611804 0.113871913 0.112309662
    ## 244        <NA> 0.112994382 0.107960685
    ## 245 0.109183966 0.112456806 0.110325377
    ## 246 0.103669455 0.106161333        <NA>
    ## 247  0.11034929 0.107437412 0.110393571
    ## 248 0.105814679 0.107261536 0.101731113
    ## 249 0.105704397 0.113010336 0.108083297
    ## 250 0.107601041 0.110555327 0.112731537
    ## 251 0.111963376 0.111256439 0.109087119
    ## 252 0.112201729 0.106150358 0.111221253
    ## 253 0.110404571  0.10790282 0.112110757
    ## 254 0.111819559  0.10801035 0.107276062
    ## 255        <NA> 0.112359508 0.108116303
    ## 256        <NA> 0.107815484        <NA>
    ## 257 0.111010329 0.107208468 0.108662788
    ## 258 0.107247746 0.108624049 0.107852263
    ## 259 0.110413053 0.105684222 0.107486057
    ## 260 0.109553088 0.109083999 0.109822586
    ## 261 0.106700067 0.103447275 0.109363855
    ## 262 0.110016151 0.111912187 0.110882342
    ## 263 0.113068347 0.106739447 0.108359644
    ## 264  0.11297526 0.111840845 0.108153563
    ## 265  0.10736014 0.103412602 0.104867625
    ## 266 0.111936644 0.108544438 0.108081178
    ## 267 0.117071872 0.111997771 0.110278987
    ## 268 0.109941957 0.109059002 0.107458997
    ## 269 0.106771338 0.109148607 0.106092654
    ## 270 0.112281329 0.108625478 0.104229652
    ## 271 0.109749603 0.105062348 0.101766786
    ## 272 0.114310737        <NA>   0.1098184
    ## 273 0.111954677 0.111164524 0.113910429
    ## 274          Na 0.106680502 0.108297104
    ## 275  0.10952307 0.108223636 0.103776878
    ## 276 0.107760535  0.10915948 0.112712093
    ## 277 0.116324032 0.111921308 0.111561345
    ## 278 0.109891454 0.106144773 0.105230652
    ## 279 0.111885804 0.110751579 0.111124896
    ## 280        <NA> 0.110877524 0.108144787
    ## 281 0.116115676 0.113432231 0.109090531
    ## 282 0.110634459 0.106090678 0.111046544
    ## 283 0.109979911 0.109572352 0.108636003
    ## 284 0.110800328 0.113297202  0.10689018
    ## 285  0.10950988 0.111039211 0.108035247
    ## 286 0.115982548 0.110050338 0.110917812
    ## 287 0.109082952 0.111450092 0.109565108
    ## 288 0.108521814 0.109283827        <NA>
    ## 289 0.111514495 0.109334647 0.106597782
    ## 290 0.116997515 0.113761549 0.111077001
    ## 291 0.116219419 0.108497527        <NA>
    ## 292        <NA> 0.108201473        <NA>
    ## 293 0.113907651 0.116341044 0.108183992
    ## 294 0.113651628 0.109358363 0.109229675
    ## 295 0.107768124 0.109290972 0.107677523
    ## 296 0.110199541 0.111853532 0.110125816
    ## 297 0.106714243 0.106435844 0.111616836
    ## 298 0.110930495 0.109040278 0.106643493
    ## 299 0.111223702 0.109013934 0.108802433
    ## 300 0.111561994 0.112290273 0.105329408
    ## 301 0.115979489 0.118015523 0.112190486
    ## 302 0.113987558 0.112578082        <NA>
    ## 303 0.113913322  0.10932139        <NA>
    ## 304        <NA> 0.109814774 0.102045489
    ## 305 0.108546849 0.102970337 0.107146837
    ## 306 0.110423346 0.107215863 0.112984185
    ## 307 0.113048282 0.110042851 0.109820332
    ## 308 0.104537415 0.108523479 0.111256162
    ## 309 0.111160149 0.109172259 0.109381538
    ## 310 0.113202621 0.110916573 0.106187184
    ## 311 0.112249598 0.115404869 0.111303622
    ## 312 0.111362252 0.109486086 0.115596082
    ## 313 0.109834068 0.108219294 0.108880295
    ## 314 0.110279471 0.109730294 0.106944687
    ## 315   0.1065023 0.103627959 0.105508768
    ## 316 0.114662559 0.114035932  0.11160086
    ## 317 0.107350371 0.103459996 0.110392014
    ## 318        <NA> 0.110478446 0.109628693
    ## 319 0.106495998        <NA> 0.103131543
    ## 320 0.105360808 0.109739168 0.104887218
    ## 321 0.112236435  0.11320741  0.11110656
    ## 322        <NA> 0.104006159 0.107353915
    ## 323  0.10804157 0.109605801        <NA>
    ## 324 0.112317119 0.110036624        <NA>
    ## 325 0.112288201 0.109383084 0.111657097
    ## 326 0.107696427 0.111126742 0.105490944
    ## 327 0.107022236 0.107180728 0.113024817
    ## 328 0.105943608  0.11360883 0.109912138
    ## 329        <NA>        <NA> 0.105607142
    ## 330 0.111248602 0.111423406 0.111403693
    ## 331 0.108952132 0.111533928  0.10741593
    ## 332 0.109694398        <NA> 0.107521406
    ## 333 0.108849157  0.10870563 0.107703482
    ## 334 0.105374421 0.111752382 0.111579106
    ## 335 0.111727067 0.102941601 0.104574502
    ## 336 0.108736248  0.11236736 0.111010295
    ## 337  0.10645713   0.1134974 0.108602524
    ## 338        <NA> 0.110497676 0.109453551
    ## 339          Na          Na 0.108283938
    ## 340 0.113778394 0.107296578 0.109604379
    ## 341        <NA>    0.112093 0.104375674
    ## 342 0.111349996 0.108476817 0.106779606
    ## 343 0.108101136 0.110134979  0.11098663
    ## 344 0.116096237 0.108574278 0.110701158
    ## 345 0.113857059 0.109308933 0.109643453
    ## 346 0.113612053 0.112858701 0.105875249
    ## 347        <NA> 0.112345414 0.111621207
    ## 348 0.113527599 0.112651493 0.109620327
    ## 349 0.115099192 0.112269423 0.111311591
    ## 350 0.112005666 0.107506531 0.108281493
    ## 351 0.110853382 0.107816785 0.107352739
    ## 352 0.103712548 0.103892805 0.106774995
    ## 353 0.114759173   0.1114577 0.113260306
    ## 354        <NA> 0.110695295        <NA>
    ## 355 0.112225585 0.109015141 0.108830284
    ## 356 0.115017143 0.110124237 0.111642089
    ## 357        <NA>        <NA> 0.112550817
    ## 358 0.106592298 0.109460717   0.1008376
    ## 359 0.110385854 0.109035814 0.107564188
    ## 360 0.110103497 0.112970507 0.108582532
    ## 361 0.109071931 0.103038004 0.102900066
    ## 362 0.111873356 0.108872776 0.111261354
    ## 363 0.113789554 0.107122912 0.108727152
    ## 364 0.110582059  0.11202907 0.105121096
    ## 365 0.112908654  0.11424814 0.110175098
    ## 366 0.109995956        <NA> 0.113725839
    ## 367 0.115212181 0.113150469 0.112476619
    ## 368 0.112152791 0.108346107 0.109229455
    ## 369 0.105177412 0.104139524 0.109674178
    ## 370 0.112476877 0.114786475        <NA>
    ## 371 0.108349732 0.109511885        <NA>
    ## 372 0.109917251 0.108258176 0.104794024
    ## 373  0.10789639 0.104688733          Na
    ## 374  0.10815293 0.107072946 0.106135638
    ## 375 0.111288572 0.106142726 0.114108779
    ## 376 0.107494751        <NA> 0.107222869
    ## 377 0.109824882 0.114763061 0.114664764
    ## 378 0.110864882 0.110135116 0.113347124
    ## 379 0.110209973        <NA> 0.105284681
    ## 380 0.112962497 0.111523124 0.105103376
    ## 381 0.114966008 0.113233396 0.110902281
    ## 382 0.111139421 0.109152422 0.109602494
    ## 383 0.110079891 0.108484313 0.107956096
    ## 384 0.109373128 0.109307354 0.109312173
    ## 385 0.105705433 0.105315475 0.108028021
    ## 386 0.108039492 0.104458211  0.10778224
    ## 387 0.111484023 0.112740921 0.105904603
    ## 388  0.11388343 0.113533418 0.110892797
    ## 389 0.108029282 0.109944121        <NA>
    ## 390 0.109070689 0.108450194 0.106333398
    ## 391  0.10911387 0.108618298 0.105794803
    ## 392 0.105547155 0.107949234        <NA>
    ## 393 0.110050517        <NA> 0.102225526
    ## 394        <NA> 0.111752933 0.109090812
    ## 395 0.114093577 0.113339185 0.108094695
    ## 396 0.109140882 0.111784382 0.109038636
    ## 397 0.106479322 0.107866499 0.107554171
    ## 398 0.109132555 0.111064613        <NA>
    ## 399 0.109345677 0.109233323 0.108428963
    ## 400        <NA> 0.109467492 0.110308657
    ## 401 0.103724591 0.106425933 0.108418488
    ## 402 0.110888815 0.108226146 0.108759893
    ## 403 0.107983711        <NA> 0.105484627
    ## 404 0.108905792 0.105652384  0.10604638
    ## 405 0.113191559 0.105054008 0.106679047
    ## 406 0.111588415 0.109551012 0.112205359
    ## 407 0.109251204 0.112401154 0.107010352
    ## 408  0.11008985 0.106788506 0.113044637
    ## 409 0.108709817 0.108169892 0.109443157
    ## 410 0.109138644 0.106436528 0.106433783
    ## 411 0.105718947 0.105514681 0.109671392
    ## 412 0.104911411        <NA>        <NA>
    ## 413 0.112359417  0.10680939 0.110450379
    ## 414 0.113785139 0.108150086 0.108537751
    ## 415 0.114431707   0.1137278 0.109429577
    ## 416  0.10934428 0.111442617        <NA>
    ## 417 0.109323546 0.108688383 0.108075209
    ## 418 0.108361884 0.109812625 0.108399149
    ## 419 0.110668669 0.109035478 0.107674925
    ## 420 0.113835848 0.111187111 0.109214307
    ## 421 0.107605532 0.103964874 0.105055193
    ## 422 0.107412607 0.110715141        <NA>
    ## 423 0.105009479 0.111238236 0.108845336
    ## 424 0.107451301 0.108318444 0.105647539
    ## 425 0.110098963 0.111583618 0.108913147
    ## 426 0.114423322  0.11234487        <NA>
    ## 427 0.111706224 0.109712911 0.110886067
    ## 428  0.10961454 0.107045634 0.108090234
    ## 429 0.113034346        <NA>        <NA>
    ## 430        <NA> 0.108020545 0.110984951
    ## 431 0.109277554 0.108903841 0.106948706
    ## 432 0.115847696 0.109552336 0.108468762
    ## 433 0.111359897 0.111916307 0.109640853
    ## 434 0.111416661 0.108085945  0.10012247
    ## 435        <NA> 0.103392509 0.103583169
    ## 436  0.11042367 0.108223344  0.10967436
    ## 437 0.110776789 0.103173607 0.107273022
    ## 438 0.109578073        <NA> 0.109615973
    ## 439 0.102615472 0.105995796  0.10901351
    ## 440 0.109770461 0.106564458 0.106285924
    ## 441 0.111268016 0.108200866 0.110846192
    ## 442 0.113766563 0.113627495 0.111382255
    ## 443 0.111391413 0.109293994 0.109824567
    ## 444 0.110993465 0.110439488 0.109777692
    ## 445 0.110564206 0.111948352 0.105686326
    ## 446 0.106626914 0.106243479 0.104957373
    ## 447 0.114421157 0.113062703 0.109135023
    ## 448 0.114616772        <NA>        <NA>
    ## 449 0.108348057 0.108864187 0.106687822
    ## 450 0.110254455 0.108375329 0.108762325
    ## 451 0.113613587  0.11285406 0.109816686
    ## 452  0.10707184        <NA> 0.103722411
    ## 453 0.110242553 0.111167073 0.108521001
    ## 454 0.107209301        <NA> 0.105025549
    ## 455        <NA> 0.100516477 0.105967832
    ## 456 0.109726598 0.111430567 0.109383737
    ## 457 0.109159353 0.115900536 0.112619995
    ## 458 0.111334526 0.109230611 0.105973147
    ## 459 0.114942874        <NA> 0.109947017
    ## 460 0.111914804 0.104893822 0.105111863
    ## 461 0.110604278 0.104722327 0.107260583
    ## 462 0.112524173 0.108815306  0.11100606
    ## 463 0.109258812 0.112268992 0.113516834
    ## 464  0.10788113 0.111750296 0.110563091
    ## 465 0.114904251 0.109917734 0.107265883
    ## 466 0.107566501  0.10915194 0.105219974
    ## 467 0.112400645 0.105352234 0.112690811
    ## 468 0.109543928 0.108449884   0.1056868
    ## 469 0.108104159 0.111896156 0.110659401
    ## 470 0.110864882 0.106587438 0.104918776
    ## 471 0.110644645 0.108962615 0.111075379
    ## 472 0.113371917 0.112762154 0.110903612
    ## 473 0.113397136 0.110586042 0.112990595
    ## 474 0.108469817 0.107775949 0.105178037
    ## 475 0.109182887 0.110607585 0.107057538
    ## 476 0.107758828 0.107281321 0.106181816
    ## 477        <NA> 0.110035156 0.107234758
    ## 478 0.109855229 0.110951271 0.105861634
    ## 479 0.113132987 0.108902038 0.109449907
    ## 480 0.115109381 0.116004489 0.112260161
    ## 481 0.111492905 0.110104053        <NA>
    ## 482 0.111358448 0.110509854 0.110541984
    ## 483 0.110672861 0.109064952 0.109161341
    ## 484 0.109491179 0.104448142 0.108636703
    ## 485 0.112133216 0.111399722 0.108836759

There are 391 participants appear in only the amyloid datasets, which
means some basic demographic information were missed out at the study
baseline.

``` r
combine_df=
  inner_join(baseline_df,mci_amyloid_df,by="id")
full_data_df=
  na.omit(combine_df)
write.csv(combine_df, "combined_data.csv", row.names = FALSE)
write.csv(full_data_df, "full_data.csv", row.names = FALSE)
```

There 94 participants appear in both datasets, and there are only 66
participants completing the whole follow-up survey.
