---
title: "p8105_hw2_ah4167"
author: "Aiying Huang"
date: "2023-09-26"
output: github_document
---
# problem 1

```{r}
library(tidyverse)
```
First, clean the data in pols-month.csv. Use separate() to break up the variable mon into integer variables year, month, and day; replace month number with month name; create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.

```{r}
pols_month_df=
  read.csv("./data/fivethirtyeight_datasets/pols-month.csv")|>
  separate(
           col="mon",
           into=c("year","month","day"),
           sep="-")|>
  mutate(
    month=case_match(
      month,
    "01"~"Jan",
    "02"~"Feb",
    "03"~"Mar",
    "04"~"Apr",
    "05"~"May",
    "06"~"June",
    "07"~"July",
    "08"~"Aug",
    "09"~"Sept",
    "10"~"Oct",
    "11"~"Nov",
    "12"~"Dec")
  )|>
  mutate(
    president=case_match(
      prez_gop,
    0~"dem",
    1~"gop"
    )
  )|>
  select(-starts_with("prez_"))|>
  select(-day)
```



